"""Conversation transcript logger.

Appends every user ↔ Ruchi exchange to a human-readable Markdown file
so the whole conversation is preserved in text form. Two files are
maintained:

* ``transcripts/conversation.md`` — append-only master log across all
  sessions.
* ``transcripts/YYYY-MM-DD.md``   — per-day log.

Each entry records the timestamp, session id, mode, the user's words,
Ruchi's reply, and any function-calling tools that fired.

Set ``TRANSCRIPT_DIR`` to change the output directory, or
``TRANSCRIPT_ENABLED=0`` to turn logging off.
"""
from __future__ import annotations

import os
import threading
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent

DEFAULT_DIR = _PROJECT_ROOT / "transcripts"

_lock = threading.Lock()


def _enabled() -> bool:
    return os.getenv("TRANSCRIPT_ENABLED", "1") not in ("0", "false", "False", "no")


def transcript_dir() -> Path:
    d = Path(os.getenv("TRANSCRIPT_DIR", str(DEFAULT_DIR)))
    d.mkdir(parents=True, exist_ok=True)
    return d


def _fmt_ts(ts: datetime | None = None) -> str:
    return (ts or datetime.now()).strftime("%Y-%m-%d %H:%M:%S")


def _fmt_tools(tool_calls: Iterable[dict[str, Any]] | None) -> str:
    """Render fired tools as a compact inline code line."""
    calls = list(tool_calls or [])
    if not calls:
        return ""
    bits = []
    for tc in calls:
        name = tc.get("name", "?")
        args = tc.get("args") or {}
        if args:
            arg_str = ", ".join(f"{k}={v!r}" for k, v in args.items())
            bits.append(f"{name}({arg_str})")
        else:
            bits.append(f"{name}()")
    return "`tools: " + ", ".join(bits) + "`"


def _append(path: Path, text: str) -> None:
    with _lock:
        with path.open("a", encoding="utf-8") as f:
            f.write(text)


def _ensure_header(path: Path, title: str) -> None:
    if not path.exists() or path.stat().st_size == 0:
        _append(
            path,
            f"# {title}\n\n"
            f"_Auto-generated by Ruchi. Newest entries appended at the bottom._\n\n"
            f"---\n\n",
        )


def log_turn(
    *,
    session_id: str,
    mode: str,
    user_text: str,
    assistant_text: str,
    tool_calls: list[dict[str, Any]] | None = None,
    events: list[dict[str, Any]] | None = None,
    provider: str | None = None,
    ts: datetime | None = None,
) -> None:
    """Append one full turn (user + Ruchi + tools) to the transcript."""
    if not _enabled():
        return
    now = ts or datetime.now()
    stamp = _fmt_ts(now)

    lines: list[str] = []
    lines.append(f"### {stamp} · session `{session_id[:8]}` · {mode}\n")
    lines.append(f"**You:** {user_text.strip()}\n")
    tools_line = _fmt_tools(tool_calls)
    if tools_line:
        lines.append(f"**Ruchi:** {assistant_text.strip()}\n")
        lines.append(f"{tools_line}\n")
    else:
        lines.append(f"**Ruchi:** {assistant_text.strip()}\n")
    if provider:
        lines.append(f"_provider: {provider}_\n")
    lines.append("")

    block = "\n".join(lines) + "\n"

    d = transcript_dir()
    master = d / "conversation.md"
    daily = d / f"{now.strftime('%Y-%m-%d')}.md"
    _ensure_header(master, "Ruchi — Conversation Transcript")
    _ensure_header(daily, f"Ruchi — Conversation Transcript ({now.strftime('%Y-%m-%d')})")
    _append(master, block)
    _append(daily, block)


def log_note(session_id: str, text: str, *, ts: datetime | None = None) -> None:
    """Append a non-turn note (session start/end, errors, etc.)."""
    if not _enabled():
        return
    now = ts or datetime.now()
    d = transcript_dir()
    master = d / "conversation.md"
    _ensure_header(master, "Ruchi — Conversation Transcript")
    _append(master, f"> _{_fmt_ts(now)} · `{session_id[:8]}` · {text}_\n\n")


def read_transcript() -> str:
    """Return the full master transcript as text (empty string if none)."""
    path = transcript_dir() / "conversation.md"
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def transcript_files() -> list[dict[str, Any]]:
    """List transcript files with size + modified time."""
    d = transcript_dir()
    out = []
    for p in sorted(d.glob("*.md")):
        st = p.stat()
        out.append(
            {
                "name": p.name,
                "bytes": st.st_size,
                "modified": datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
            }
        )
    return out


def clear_transcript() -> None:
    """Delete all transcript files."""
    d = transcript_dir()
    for p in d.glob("*.md"):
        try:
            p.unlink()
        except OSError:
            pass


__all__ = [
    "log_turn",
    "log_note",
    "read_transcript",
    "transcript_files",
    "clear_transcript",
    "transcript_dir",
]
